// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(annexe)/aspects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aspects">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/aspects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/asteroides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asteroides">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/asteroides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/cuspides-des-maisons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuspides-des-maisons">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/cuspides-des-maisons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/les-decans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/les-decans">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/les-decans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/lilith/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lilith">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/lilith/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/maisons-derivees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maisons-derivees">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/maisons-derivees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/maitrises/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maitrises">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/maitrises/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/noeuds-lunaires/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/noeuds-lunaires">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/noeuds-lunaires/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/points-fictifs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/points-fictifs">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/points-fictifs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/retrogrades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retrogrades">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/retrogrades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/revolution-solaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/revolution-solaire">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/revolution-solaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/synastrie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/synastrie">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/synastrie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(annexe)/transits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transits">> = Specific
  const handler = {} as typeof import("../../../app/(annexe)/transits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/a-propos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/a-propos">> = Specific
  const handler = {} as typeof import("../../../app/a-propos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auteur/stephane-gamot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auteur/stephane-gamot">> = Specific
  const handler = {} as typeof import("../../../app/auteur/stephane-gamot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/confidentialite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/confidentialite">> = Specific
  const handler = {} as typeof import("../../../app/confidentialite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dictionnaire-astrologique/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dictionnaire-astrologique">> = Specific
  const handler = {} as typeof import("../../../app/dictionnaire-astrologique/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maisons/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maisons/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/maisons/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mentions-legales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentions-legales">> = Specific
  const handler = {} as typeof import("../../../app/mentions-legales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/planetes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planetes/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/planetes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signes/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/signes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/views">> = Specific
  const handler = {} as typeof import("../../../app/api/views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
