// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/a-propos" | "/[locale]/aspects" | "/[locale]/asteroides" | "/[locale]/astro-psychologie" | "/[locale]/astrologie-horaire" | "/[locale]/astrologie-medicale" | "/[locale]/auteur/stephane-gamot" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/blog/tag/[slug]" | "/[locale]/confidentialite" | "/[locale]/cuspides-des-maisons" | "/[locale]/dictionnaire-astrologique" | "/[locale]/les-decans" | "/[locale]/lilith" | "/[locale]/maisons-derivees" | "/[locale]/maisons/[slug]" | "/[locale]/maitrises" | "/[locale]/mentions-legales" | "/[locale]/noeuds-lunaires" | "/[locale]/planetes/[slug]" | "/[locale]/points-fictifs" | "/[locale]/retrogrades" | "/[locale]/revolution-solaire" | "/[locale]/signes/[slug]" | "/[locale]/significateurs" | "/[locale]/synastrie" | "/[locale]/transits"
type AppRouteHandlerRoutes = "/api/views"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = "/blog/comprendre-son-signe-astrologique-et-son-ascendant"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/a-propos": { "locale": string; }
  "/[locale]/aspects": { "locale": string; }
  "/[locale]/asteroides": { "locale": string; }
  "/[locale]/astro-psychologie": { "locale": string; }
  "/[locale]/astrologie-horaire": { "locale": string; }
  "/[locale]/astrologie-medicale": { "locale": string; }
  "/[locale]/auteur/stephane-gamot": { "locale": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/blog/tag/[slug]": { "locale": string; "slug": string; }
  "/[locale]/confidentialite": { "locale": string; }
  "/[locale]/cuspides-des-maisons": { "locale": string; }
  "/[locale]/dictionnaire-astrologique": { "locale": string; }
  "/[locale]/les-decans": { "locale": string; }
  "/[locale]/lilith": { "locale": string; }
  "/[locale]/maisons-derivees": { "locale": string; }
  "/[locale]/maisons/[slug]": { "locale": string; "slug": string; }
  "/[locale]/maitrises": { "locale": string; }
  "/[locale]/mentions-legales": { "locale": string; }
  "/[locale]/noeuds-lunaires": { "locale": string; }
  "/[locale]/planetes/[slug]": { "locale": string; "slug": string; }
  "/[locale]/points-fictifs": { "locale": string; }
  "/[locale]/retrogrades": { "locale": string; }
  "/[locale]/revolution-solaire": { "locale": string; }
  "/[locale]/signes/[slug]": { "locale": string; "slug": string; }
  "/[locale]/significateurs": { "locale": string; }
  "/[locale]/synastrie": { "locale": string; }
  "/[locale]/transits": { "locale": string; }
  "/api/views": {}
  "/blog/comprendre-son-signe-astrologique-et-son-ascendant": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
