// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[locale]/(annexe)/aspects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/aspects">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/aspects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/asteroides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/asteroides">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/asteroides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/astro-psychologie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/astro-psychologie">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/astro-psychologie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/astrologie-horaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/astrologie-horaire">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/astrologie-horaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/astrologie-medicale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/astrologie-medicale">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/astrologie-medicale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/cuspides-des-maisons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cuspides-des-maisons">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/cuspides-des-maisons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/les-decans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/les-decans">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/les-decans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/lilith/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/lilith">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/lilith/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/maisons-derivees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/maisons-derivees">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/maisons-derivees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/maitrises/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/maitrises">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/maitrises/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/noeuds-lunaires/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/noeuds-lunaires">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/noeuds-lunaires/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/points-fictifs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/points-fictifs">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/points-fictifs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/retrogrades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/retrogrades">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/retrogrades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/revolution-solaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/revolution-solaire">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/revolution-solaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/significateurs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/significateurs">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/significateurs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/synastrie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/synastrie">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/synastrie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(annexe)/transits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/transits">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(annexe)/transits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/a-propos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/a-propos">> = Specific
  const handler = {} as typeof import("../../app/[locale]/a-propos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/auteur/stephane-gamot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auteur/stephane-gamot">> = Specific
  const handler = {} as typeof import("../../app/[locale]/auteur/stephane-gamot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/blog/tag/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/tag/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/blog/tag/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/confidentialite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/confidentialite">> = Specific
  const handler = {} as typeof import("../../app/[locale]/confidentialite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dictionnaire-astrologique/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dictionnaire-astrologique">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dictionnaire-astrologique/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/maisons/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/maisons/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/maisons/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/mentions-legales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/mentions-legales">> = Specific
  const handler = {} as typeof import("../../app/[locale]/mentions-legales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/planetes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/planetes/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/planetes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/signes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/signes/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/signes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/views">> = Specific
  const handler = {} as typeof import("../../app/api/views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
